[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "mi_modulo"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
geo = "0.30.0"
geo-clipper = "0.9.0"
geo-types = "0.7.16"
